"""Regenerate the unexecuted Colab notebook from explicit cells."""
import json
from pathlib import Path

cells = []
def md(text): cells.append({"cell_type":"markdown","metadata":{},"source":text.splitlines(True)})
def code(text): cells.append({"cell_type":"code","metadata":{},"source":text.splitlines(True),"execution_count":None,"outputs":[]})
md("# RoadVision AI · Colab training and evaluation\n\nThis notebook has not been executed. Select Runtime > Change runtime type > T4 GPU. Training consumes GPU time and disk. Start with the official India subset; do not describe it as the full RDD2022 dataset. Read the official dataset and Ultralytics terms before downloading. No credentials belong in this notebook.")
code("!nvidia-smi\nimport torch\nassert torch.cuda.is_available(), 'Select a GPU runtime before training.'")
code("from google.colab import drive\ndrive.mount('/content/drive')\nfrom pathlib import Path\nimport datetime\nRUN_ID = datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%d-%H%M%S')\nSAVE = Path('/content/drive/MyDrive/RoadVisionAI') / RUN_ID\nSAVE.mkdir(parents=True, exist_ok=False)")
code("REPO = 'https://github.com/techky-Kabilan/Deep-Learning-Lab.git'\nBRANCH = 'roadvision-ai-mini-project'\n!git clone --depth 1 --branch $BRANCH $REPO /content/Deep-Learning-Lab\n%cd /content/Deep-Learning-Lab/mini-projects/roadvision-ai\n!pip -q install -r requirements.txt\n!git rev-parse HEAD > /content/roadvision-commit.txt\n!pip freeze > /content/roadvision-environment.txt")
md("## Retrieve the official archive\nThe India archive is about 502 MB compressed according to the official repository; extraction requires additional space. This cell downloads data only when you run it. Source and terms: https://github.com/sekilab/RoadDamageDetector . Confirm archive/hosting terms and attribute Arya et al. Dataset images are described as CC BY-SA 4.0 by the official README. Keep the archive outside Git.")
code("import urllib.request, zipfile, shutil\nURL = 'https://bigdatacup.s3.ap-northeast-1.amazonaws.com/2022/CRDDC2022/RDD2022/Country_Specific_Data_CRDDC2022/RDD2022_India.zip'\n# If the official S3 endpoint denies access, obtain data from official Figshare DOI 10.6084/m9.figshare.21431547 and place the India subset archive in Drive.\nDRIVE_ARCHIVE = None  # Example: '/content/drive/MyDrive/datasets/RDD2022_India.zip'\nARCHIVE = Path(DRIVE_ARCHIVE) if DRIVE_ARCHIVE else Path('/content/India.zip')\nRAW = Path('/content/rdd_raw')\nassert shutil.disk_usage('/content').free > 4 * 1024**3, 'Need at least 4 GB free space for the India subset; full archive needs much more.'\nif not ARCHIVE.exists():\n    try:\n        urllib.request.urlretrieve(URL, ARCHIVE)\n    except Exception as exc:\n        if ARCHIVE.exists(): ARCHIVE.unlink()\n        raise RuntimeError('Official S3 download unavailable. Obtain the official dataset from Figshare, put an India subset archive in Drive, set DRIVE_ARCHIVE, and rerun. Do not use an unverified mirror.') from exc\nRAW.mkdir(exist_ok=True)\nwith zipfile.ZipFile(ARCHIVE) as archive:\n    assert sum(m.file_size for m in archive.infolist()) < shutil.disk_usage('/content').free, 'Not enough space to extract archive.'\n    for member in archive.infolist():\n        target = (RAW / member.filename).resolve()\n        if not target.is_relative_to(RAW.resolve()):\n            raise ValueError('Unsafe archive member')\n    archive.extractall(RAW)\nprint('Annotated XML files:', len(list(RAW.rglob('*.xml'))))")
md("## Prepare labelled partitions\nOfficial challenge test images do not include public annotations. Local test metrics use a held-out labelled portion. Default splitting is by distinct image: correlated adjacent scenes may remain. For stronger evidence supply a JSON route/sequence manifest to prepare(). Review support for all classes before training. The output refuses to overwrite an existing dataset.")
code("from scripts.prepare_rdd2022 import prepare\nimport json\nPREPARED = Path('/content/rdd_prepared')\nprepare(RAW, PREPARED, seed=42)\nsummary = json.loads((PREPARED / 'split_summary.json').read_text())\nprint(json.dumps(summary, indent=2))\nfor split in ('train','val','test'):\n    assert all(summary['objects'][split].get(c, 0) > 0 for c in ('D00','D10','D20','D40')), f'Missing class support in {split}'\nshutil.copy2(PREPARED / 'split_manifest.json', SAVE / 'split_manifest.json')\nshutil.copy2(PREPARED / 'split_summary.json', SAVE / 'split_summary.json')")
md("## Fine-tune pretrained YOLOv8n\nThese are starting hyperparameters, not validated optimum settings. Reduce batch if GPU memory is insufficient. Do not tune on the held-out test set. Restart the runtime if required by the dependency installer before this cell.")
code("from ultralytics import YOLO\nmodel = YOLO('yolov8n.pt')\nmodel.train(data=str(PREPARED / 'data.yaml'), epochs=50, imgsz=640, batch=16, device=0, seed=42, deterministic=True, patience=10, workers=2, project='/content/runs', name='roadvision', exist_ok=False)\nBEST = Path(model.trainer.best)\nassert BEST.is_file()\nshutil.copy2(BEST, SAVE / 'best.pt')\nshutil.copytree(model.trainer.save_dir, SAVE / 'training')")
md("## Final held-out evaluation\nSave aggregate/per-class metrics, confusion matrices (including background), PR curves and provenance. Precision/recall summary values use the library operating point. The low validation confidence threshold is intentional for AP ranking. Inspect false positives and false negatives; document missing/rare classes and domain shift.")
code("from scripts.evaluate import evaluate\nEVALUATION = evaluate(BEST, PREPARED / 'data.yaml', Path('/content/final-evaluation'), split='test', device='0')\nshutil.copytree(EVALUATION, SAVE / 'evaluation')\nshutil.copy2('/content/roadvision-commit.txt', SAVE / 'commit.txt')\nshutil.copy2('/content/roadvision-environment.txt', SAVE / 'environment.txt')\nprint((EVALUATION / 'metrics.json').read_text())")
code("from IPython.display import Image, display\nfor name in ('confusion_matrix.png','confusion_matrix_normalized.png','BoxPR_curve.png'):\n    path = EVALUATION / name\n    if path.exists(): display(Image(filename=str(path)))\nprint('Artifacts saved:', SAVE)")
md("## Bring the model into Streamlit\nDownload best.pt from the run folder to weights/best.pt. Keep weights and data out of Git. Update MODEL_CARD.md and the report only from the saved evaluation evidence. Capture real inference screenshots after installing the checkpoint. The checked-in screenshots use explicitly labelled synthetic fixtures and do not demonstrate model quality.")
notebook = {"cells":cells,"metadata":{"colab":{"name":"RoadVision_AI_Training.ipynb"},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":5}
if __name__ == '__main__':
    target = Path(__file__).resolve().parents[1] / 'notebooks/train_colab.ipynb'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(notebook, indent=2), encoding='utf-8')
